[package]
name = "marjapussi"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.13.0"
strum = "0.26.3"
strum_macros = "0.26.4"
chrono = "0.4"
rand = "0.8.5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_with = "3.3.0"
